# Generated by Django 3.2.5 on 2021-08-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_auto_20210802_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='repayment_amount',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
    ]
