# Generated by Django 3.2.5 on 2021-08-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_alter_loan_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
